package com.bookapp.presentation.viewmodel

import com.bookapp.domain.models.Book
import com.bookapp.domain.usecase.AddBookUseCase
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.datetime.Clock

class AddBookViewModel(
    private val addBookUseCase: AddBookUseCase
) : ViewModel() {

    private val _isSuccess = MutableStateFlow(false)
    val isSuccess: StateFlow<Boolean> = _isSuccess.asStateFlow()

    private val _isLoading = MutableStateFlow(false)
    val isLoading: StateFlow<Boolean> = _isLoading.asStateFlow()

    fun saveBook(title: String, description: String, pageCount: Int, excerpt: String) {
        viewModelScope.launch {
            _isLoading.value = true
            try {
                // Assuming ID is generated by remote or we generate random ID
                val book = Book(
                    id = Clock.System.now().toEpochMilliseconds(),
                    title = title,
                    description = description,
                    pageCount = pageCount,
                    excerpt = excerpt,
                    publishDate = Clock.System.now().toString()
                )
                addBookUseCase(book)
                _isSuccess.value = true
            } catch (e: Exception) {
                e.printStackTrace()
            } finally {
                _isLoading.value = false
            }
        }
    }
}
